spring:
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:tcp://0.0.0.0/C:/app/workspace/h2-2023-09-17/h2/data/jwt}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:sa}
  jpa:
    database-platform: ${SPRING_DATASOURCE_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        show_sql: true
    open-in-view: false
  security:
    user:
      name: test
      password: test
      roles: USER, ADMIN

oauth2:
  google:
    client_id: 485784788447-t3irsd8ig19i9i06g9q4s7g9kcej85uu.apps.googleusercontent.com
    client_secret: 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
    redirect_uri: http://localhost:9999/auth/google/callback
    scope: profile email
  naver:
    client_id: OUzv9kOasKTzle3Myc4P
    client_secret: pNN1onHa59
    redirect_uri: http://localhost:9999/auth/naver/callback
    scope: name email profile_image

jwt:
  secretKey: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret

cloud:
  aws:
    s3:
      bucket: fluo-bucket
      path: ${SPRING_S3_PATH}
    credentials:
      access-key: ${SPRING_S3_ACCESS_KEY}
      secret-key: ${SPRING_S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


file:
  path:
    image: ${FILE_PATH_IMAGE:/}

logging:
  level:
    com.golapadeok.fluo: debug
    org.hibernate.orm.jdbc.bind: trace
server:
  port: 9999
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
server:
  port: 8090
oauth2:
  google:
    client_id: ${OAUTH_GOOGLE_CLIENT_ID}
    client_secret: ${OAUTH_GOOGLE_CLIENT_SECRET_ID}
    redirect_uri: ${OAUTH_GOOGLE_REDIRECT_URI}
    scope: profile email
  naver:
    client_id: ${OAUTH_NAVER_CLIENT_ID}
    client_secret: ${OAUTH_NAVER_CLIENT_SECRET_ID}
    redirect_uri: ${OAUTH_NAVER_REDIRECT_URI}
    scope: name email profile_image
jwt:
  secretKey: ${SPRING_JWT_SECRET_KEY}
---
spring:
  config:
    activate:
      on-profile: blue
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: green
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
server:
  port: 8081